# Generated by Django 4.1.7 on 2023-04-18 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_user_followers_alter_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='network/images/posts'),
        ),
    ]
