# Generated by Django 4.1.7 on 2023-04-19 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_post_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, default='network/images/profile_pictures/default.png', null=True, upload_to='network/images/profile_pictures'),
        ),
    ]
