# Generated by Django 4.1.7 on 2023-04-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_user_bookmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='network/images/comments'),
        ),
    ]
