# Generated by Django 4.1.7 on 2023-05-04 21:18

from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0018_alter_post_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to='media_CM/images/posts'),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, default='media_CM/images/profile_pictures/default.png', null=True, storage=storages.backends.s3boto3.S3Boto3Storage(), upload_to='media_CM/images/profile_pictures'),
        ),
    ]
